// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crlrmhvvrnbmkezdtemu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybHJtaHZ2cm5ibWtlemR0ZW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjE0NzcsImV4cCI6MjA2OTM5NzQ3N30.WQNnMRTmTyBeFCRLvdOoOL1JmOVh9VMzjUJvnjoCLcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});